[package]
name = "jail"
version = "0.0.0-alpha1"
authors = ["Fabian Freyer <fabian.freyer@physik.tu-berlin.de>"]
description = "FreeBSD jail library"
license = "BSD-3-Clause"
repository = "https://github.com/fubarnetes/libjail-rs"
documentation = "https://docs.rs/jail/"

[lib]
name = "jail"
path = "src/lib.rs"

[badges]
maintenance = { status = "experimental" }

[dependencies]
libc = "0.2"
errno = "0.2.3"
